### ISSUE TITLE
QUIZ 1

### ISSUE THREAD

**Issue by azmanyasin** [STIA1113-GROUP-C-A211/QUIZ#1]
### **INSTRUCTION**
This quiz consists of 18 questions. To be successful with the quiz, it’s important to thoroughly read topics 1-3  in the notes.  

[Quiz 1.docx](https://github.com/STIA1113-GROUP-C-A211/QUIZ/files/7834339/Quiz.1.docx)

### **SUBMISSION**

1.	Submit your answer (file) in GitHub.
2.	Due : 9 Jan 2022 (11.00 am)

**Comment by ChooKuaiFern277673** [comment]
https://github.com/ChooKuaiFern277673/QUIZ1.git

**Comment by TANGWEICHIANG** [comment]
https://github.com/TANGWEICHIANG/Quiz.git

**Comment by LimHuiQi** [comment]
https://github.com/STIA-1113-GROUP-C-LIMHUIQI/QUIZ-1.git

**Comment by ChooKuaiFern277673** [comment]
https://github.com/ChooKuaiFern277673/QUIZ1.git

**Comment by TANGUANXUN287471** [comment]
https://github.com/STIA1113-GROUP-C-TAN-GUAN-XUN/QUIZ.git

**Comment by WANRUIYIN-287456** [comment]
https://github.com/WANRUIYIN-287456/Quiz.git

**Comment by faraayeesha286941** [comment]
https://github.com/STIA-1113-GROUP-C-FARA-AYEESHA/Quiz.git

**Comment by HOWAIKIAT287156** [comment]
https://github.com/STIA-1113-GROUP-C-HO-WAI-KIAT/QUIZ-1.git

**Comment by zafirahnuraina** [comment]
https://github.com/STIA-1113-GROUP-C-ZAFIRAH/QUIZ1.git

**Comment by TOHVINPING286681** [comment]
https://github.com/STIA-1113-GROUP-C-Toh-Vin-Ping/Quiz1.git

**Comment by JunHan016** [comment]
https://github.com/STIA1113-GROUP-C/QUIZ.git

**Comment by 270659teyengzin** [comment]
https://github.com/STIA-1113-GROUP-C-ZIN/QUIZ1.git

**Comment by RayyanKamal28462** [comment]
https://github.com/RayyanKamal28462/quiz1.git

**Comment by ChoongQianYu-286623** [comment]
https://github.com/STIA-1113-GROUP-C-CHOONG-QIAN-YU/QUIZ

**Comment by Daniel-Fikrey-287148** [comment]
https://github.com/STIA-1113-GRP-C/Quiz-Programming.git

**Comment by AnisShafiqah** [comment]
https://github.com/STIA1113-GROUP-C-ANIS-SHAFIQAH/QUIZ-1.git

**Comment by Haikal283950** [comment]
https://github.com/STIA1113-GROUP-C-HAIKAL/Quiz1.git

**Comment by GohKoonLoong** [comment]
https://github.com/STIA-1113-GROUP-C-GOH/Quiz-1.git

**Comment by Yasriroslan** [comment]
https://github.com/Yasriroslan/QUIZ.git

**Comment by Aimeldaniel** [comment]
https://github.com/STIA-1113-GROUP-C-AIMEL/Quiz.git

**Comment by ANDYSONJUNIS285676** [comment]
https://github.com/STIA-1113-GROUP-C-ANDY/QUIZ-1.git

**Comment by KorJunXiang** [comment]
https://github.com/STIA1113-GROUP-C-KOR-JUN-XIANG/Quiz.git

**Comment by Laila1911** [comment]
https://github.com/STIA-1113-GROUP-C-LAILA/QUIZ.git

**Comment by NorAisyah286982** [comment]
https://github.com/STIA-1113-GROUP-C-Nor-Aisyah/QUIZ1.git

**Comment by AQILNAJJAH** [comment]
https://github.com/STIA1113GROUP-C-PROGRAMMING-1/QUIZ.git

**Comment by NurfarahWahida1504** [comment]
https://github.com/STIA-1113-GROUP-C-NURFARAH/QUIZ.git

**Comment by ANGKAIZI286043** [comment]
https://github.com/STIA1113-GROUP-C-ANGKAIZI/Quiz-1.git

**Comment by Song-Zhuangqing** [comment]
https://github.com/STIA1113-GROUP-C-SongZhuangqing/quiz1.git

**Comment by AyshaSofea18** [comment]
https://github.com/STIA-1113-GROUP-C-Wan-Aysha-Sofea/QUIZ-1.git

**Comment by NurfarahWahida1504** [comment]
https://github.com/STIA-1113-GROUP-C-NURFARAH/QUIZ.git

**Comment by NikHanis286961** [comment]
https://github.com/STIA-1113-GROUP-C-Nik-Hanis/QUIZ-1-.git

**Comment by nuraisyah01** [comment]
https://github.com/STIA-1113-GROUP-C-NURAISYAH/QUIZ.git

**Comment by NurAlyaBintiMohdIzazi** [comment]
https://github.com/STIA1113-GROUP-C-AlyaIzazi/QUIZ1.git

**Comment by azyyatiadlin** [comment]
https://github.com/azyyatiadlin/Quiz.git

**Comment by AfiqImran-286997** [comment]
https://github.com/STIA-1113-GROUP-C-AFIQ-IMRAN/QUIZ1.git

**Comment by Seraafiqah** [comment]
https://github.com/Seraafiqah/QUIZ-1.git

**Comment by IntanSyamimi286735** [comment]
https://github.com/STIA1113-GROUP-C-IntanSyamimi/Quiz.git

**Comment by aainulamirahh** [comment]
https://github.com/STIA-1113-GROUP-C-Ainul-Amirah/QUIZ-1.git
